services:
  web:
    build: ghcr.io/erikapption/geomap-fsdh:latest
    ports:
      - "8080:80"
    volumes:
      #- ./data:/usr/local/apache2/htdocs/data
      #- ./geojson:/usr/local/apache2/htdocs/geojson
      - ./data:/mnt/fsdh/data
      - ./geojson:/mnt/fsdh/geojson

      