services:
  web:
    image: ghcr.io/erikapption/geomap-fsdh:latest
    ports:
      - "8080:80"
    volumes:
    #local setup
    #  - ./data:/mnt/fsdh/data
    #  - ./geojson:/mnt/fsdh/geojson
    #FSDH
      - datahub-blob:/mnt/fsdh

      